name: crc32
version: 0.2.0
description: A cyclic redundancy check calculator for Dart written in pure Dart.
homepage: http://github.com/kaisellgren/CRC32

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  test: any
